/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated.leaderboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated.pro'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated.rewards'
import { Route as ApiTestEndpointRouteImport } from './routes/api/test-endpoint'
import { Route as AuthenticatedLessonLevelRouteImport } from './routes/_authenticated.lesson.$level'
import { Route as AuthenticatedPaymentFailedRouteImport } from './routes/_authenticated.payment.failed'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated.payment.success'
import { Route as ApiPublicPaytrCallbackRouteImport } from './routes/api/public/paytr/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTestEndpointRoute = ApiTestEndpointRouteImport.update({
  id: '/api/test-endpoint',
  path: '/api/test-endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLessonLevelRoute =
  AuthenticatedLessonLevelRouteImport.update({
    id: '/lesson/$level',
    path: '/lesson/$level',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentFailedRoute =
  AuthenticatedPaymentFailedRouteImport.update({
    id: '/payment/failed',
    path: '/payment/failed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaytrCallbackRoute = ApiPublicPaytrCallbackRouteImport.update({
  id: '/api/public/paytr/callback',
  path: '/api/public/paytr/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pro': typeof AuthenticatedProRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/api/test-endpoint': typeof ApiTestEndpointRoute
  '/lesson/$level': typeof AuthenticatedLessonLevelRoute
  '/payment/failed': typeof AuthenticatedPaymentFailedRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/api/public/paytr/callback': typeof ApiPublicPaytrCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pro': typeof AuthenticatedProRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/api/test-endpoint': typeof ApiTestEndpointRoute
  '/lesson/$level': typeof AuthenticatedLessonLevelRoute
  '/payment/failed': typeof AuthenticatedPaymentFailedRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/api/public/paytr/callback': typeof ApiPublicPaytrCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/api/test-endpoint': typeof ApiTestEndpointRoute
  '/_authenticated/lesson/$level': typeof AuthenticatedLessonLevelRoute
  '/_authenticated/payment/failed': typeof AuthenticatedPaymentFailedRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/api/public/paytr/callback': typeof ApiPublicPaytrCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/pro'
    | '/profile'
    | '/rewards'
    | '/api/test-endpoint'
    | '/lesson/$level'
    | '/payment/failed'
    | '/payment/success'
    | '/api/public/paytr/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/pro'
    | '/profile'
    | '/rewards'
    | '/api/test-endpoint'
    | '/lesson/$level'
    | '/payment/failed'
    | '/payment/success'
    | '/api/public/paytr/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/pro'
    | '/_authenticated/profile'
    | '/_authenticated/rewards'
    | '/api/test-endpoint'
    | '/_authenticated/lesson/$level'
    | '/_authenticated/payment/failed'
    | '/_authenticated/payment/success'
    | '/api/public/paytr/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTestEndpointRoute: typeof ApiTestEndpointRoute
  ApiPublicPaytrCallbackRoute: typeof ApiPublicPaytrCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/test-endpoint': {
      id: '/api/test-endpoint'
      path: '/api/test-endpoint'
      fullPath: '/api/test-endpoint'
      preLoaderRoute: typeof ApiTestEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lesson/$level': {
      id: '/_authenticated/lesson/$level'
      path: '/lesson/$level'
      fullPath: '/lesson/$level'
      preLoaderRoute: typeof AuthenticatedLessonLevelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment/failed': {
      id: '/_authenticated/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof AuthenticatedPaymentFailedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paytr/callback': {
      id: '/api/public/paytr/callback'
      path: '/api/public/paytr/callback'
      fullPath: '/api/public/paytr/callback'
      preLoaderRoute: typeof ApiPublicPaytrCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedLessonLevelRoute: typeof AuthenticatedLessonLevelRoute
  AuthenticatedPaymentFailedRoute: typeof AuthenticatedPaymentFailedRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedLessonLevelRoute: AuthenticatedLessonLevelRoute,
  AuthenticatedPaymentFailedRoute: AuthenticatedPaymentFailedRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTestEndpointRoute: ApiTestEndpointRoute,
  ApiPublicPaytrCallbackRoute: ApiPublicPaytrCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
